adium-theme-ubuntu (0.3.4)
anoise (0.0.25)
anoise-community-extension1 (0.0.1)
anoise-community-extension3 (0.0.1)
anoise-media (0.0.17)
apt-xapian-index (0.45)
argparse (1.2.1)
backports.ssl-match-hostname (3.4.0.2)
biom-format (2.1.5)
blockify (1.8.8)
burrito (0.9.1)
burrito-fillings (0.1.1)
cairocffi (0.7.2)
cffi (1.5.2)
chardet (2.0.1)
click (6.6)
cogent (1.5.3)
colorama (0.2.5)
command-not-found (0.3)
Cython (0.23)
debtagshw (0.1)
defer (1.0.6)
dirspec (13.10)
distribute (0.6.26)
duplicity (0.6.23)
emperor (0.9.51)
functools32 (3.2.3-2)
future (0.15.2)
gdata (2.0.18)
GenAPI (0.0.8)
html5lib (0.999)
httplib2 (0.8)
lockfile (0.8)
lxml (3.3.3)
MACS (2.0.9)
MarkupSafe (0.23)
matplotlib (1.5.0)
netifaces (0.8)
numpy (1.11.0)
oauthlib (0.6.1)
oneconf (0.3.7.14.04.1)
Orange (2.7.8)
Orange-Bioinformatics (2.5.40)
PAM (0.4.2)
pandas (0.17.0)
pexpect (3.1)
pickleshare (0.5)
Pillow (2.3.0)
pip (1.5.4)
piston-mini-client (0.7.5)
Pivy (0.5.0)
ply (3.4)
ptyprocess (0.5)
pycollada (0.4)
pycparser (2.14)
pycrypto (2.6.1)
pycups (1.9.66)
pycurl (7.19.3)
pygobject (3.12.0)
pynast (1.2.2)
PyOpenGL (3.0.2)
pyOpenSSL (0.13)
pyparsing (2.0.1)
pyqi (0.3.2)
pyserial (2.6)
pysmbc (1.0.14.1)
python-apt (0.9.3.5ubuntu2)
python-dateutil (1.5)
python-debian (0.1.21-nmu2ubuntu2)
pytz (2012c)
pyxdg (0.25)
pyzmq (14.7.0)
qcli (0.1.1)
qiime (1.9.1)
qiime-default-reference (0.1.3)
reportlab (3.0)
requests (2.10.0)
requests-toolbelt (0.6.2)
scikit-bio (0.2.3)
scikit-learn (0.17)
scipy (0.16.1)
seaborn (0.6.0)
sessioninstaller (0.0.0)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 80, in run
    self.run_listing(options)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 142, in run_listing
    self.output_package_listing(installed_packages)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 151, in output_package_listing
    if dist_is_editable(dist):
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 366, in dist_is_editable
    req = FrozenRequirement.from_dist(dist, [])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 286, in from_dist
    assert len(specs) == 1 and specs[0][0] == '=='
AssertionError

Storing debug log for failure in /tmp/tmpVHD8_7
